name: Publish to Github Pages
run-name: ${{github.actor}} is deploying to Github Pages
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install and Build
        run: |
          yarn
          yarn run scrape-leipzig-statistik
          yarn run transform-leipzig-statistik
          yarn run scrape-swimming-pools
          yarn run transform-leipzig-parks
          yarn run predeploy
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
