name: Publish to Github Pages
run-name: ${{github.actor}} is deploying to Github Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install and Build
        run: |
          yarn
          yarn run predeploy
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          repository_name: https://github.com/CodeforLeipzig/leipzigmaps.git
